### ISSUE TITLE
unsecure credentials

### ISSUE THREAD

**Issue by NilsKaden** [inoue723/warikan-app#27]
Hey!

You are storing API-Keys in public files, they could be abused
https://github.com/inoue723/warikan-app/blob/master/src/config/fbConfig.js

**Comment by inoue723** [comment]
@NilsKaden 
Thanks for warning.

But firebase API keys is provided to browser even if I try to delete from public files.
see below
https://javebratt.com/hide-firebase-api/

However I should use firestore security rules to prevent app-data from abusing.
I'll do that soon.
